version: 1
formatters:
  simpleFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    formatter: simpleFormatter
    level: DEBUG
  fileHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: simpleFormatter
    level: DEBUG
    filename: logs/app.log
    maxBytes: 10485760 # 10 MB
    backupCount: 5
loggers:
  Scraper:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]
    propagate: False
  OutputWriter:
    level: DEBUG
    handlers: [ consoleHandler, fileHandler ]
    propagate: False
root:
  level: INFO
  handlers: [consoleHandler, fileHandler]